positive_words:
  - caress
  - freedom
  - health
  - love
  - peace
  - cheer
  - friend
  - heaven
  - loyal
  - pleasure
  - diamond
  - gentle
  - honest
  - lucky
  - rainbow
  - diploma
  - gift
  - honor
  - miracle
  - sunrise
  - family
  - happy
  - laughter
  - paradise
  - vacation

negative_words:
  - abuse
  - crash
  - filth
  - murder
  - sickness
  - accident
  - death
  - grief
  - poison
  - stink
  - assault
  - disaster
  - hatred
  - pollute
  - tragedy
  - bomb
  - divorce
  - jail
  - poverty
  - ugly
  - cancer
  - evil
  - kill
  - rotten
  - vomit
  - agony
  - prison
